default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: receptionist_doctor_portal_development
  # Add your PostgreSQL username and password here if needed
  # username: postgres
  # password: root
  # Ensure that the host and port are correctly configured
  host: localhost
  port: 5432

test:
  <<: *default
  database: receptionist_doctor_portal_test
  # Add your PostgreSQL username and password here if needed
  # username: postgres
  # password: root
  # Ensure that the host and port are correctly configured
  host: localhost
  port: 5432

production:
  <<: *default
  database: receptionist_doctor_portal_production
  # Add your PostgreSQL username and password here if needed
  # username: postgres
  # password: root
  # Ensure that the host and port are correctly configured
  host: localhost
  port: 5432
